### ISSUE TITLE
Build models for Account

### ISSUE THREAD

**Issue by jwilli-uccs** [UCCS-CS4300-5300/group8-fall2023#127]

**Comment by jwilli-uccs** [comment]
When the User Signs Up, a UserBillingAccount should be added to their User.

**Comment by jwilli-uccs** [comment]
methodOfPayment := CC, Cash, Check (default CC)
amountDue := 0

**Comment by BenHNet** [comment]
I'm going to take this and tweak it a bit.

Account = UserID, Email, OutstandingBalance, DefaultPaymentMethod
PaymentMethod = ID, MethodDesc
Payment = UserID, PaymentMethod, AmountPaid
